
class TrainingPipelineConfig:...
class DataIngestionConfig:...
class DataValidationConfig:...
class DataTransformationConfig:...
class DataTrainerConfig:...
class DataEvaluationConfig:...
class DataPusherConfig:...